/**
 * @theatrum/schema — L1 · dados
 *
 * Schemas persistidos v1, tipos inferidos e fronteira explícita de versão.
 * Esta é a única superfície pública do pacote.
 */

export {
  APP_NAME,
  PROJECT_EXTENSION,
  FORMAT_ID,
  SCENE_FORMAT_ID,
  PROJECT_CONTAINER_VERSION,
  SCHEMA_VERSION,
  CURRENT_SCHEMA_VERSION,
  SCENE_SCRIPT_VERSION,
} from "./branding.js";

export {
  FiniteNumberSchema,
  NonNegativeNumberSchema,
  PositiveNumberSchema,
  FrameSchema,
  Vec2Schema,
  Vec3Schema,
  LongitudeLatitudeSchema,
  ColorSchema,
  IdentifierSchema,
  NonEmptyStringSchema,
  JsonObjectSchema,
  type Frame,
  type Vec2,
  type Vec3,
  type Color,
} from "./primitives.js";

export {
  EasingHandleSchema,
  SpatialHandlesSchema,
  keyframeSchema,
  animatablePropertySchema,
  UnknownAnimatablePropertySchema,
  NumberAnimatablePropertySchema,
  Vec2AnimatablePropertySchema,
  FrameAnimatablePropertySchema,
  type EasingHandle,
  type SpatialHandles,
  type Keyframe,
  type AnimatableProperty,
} from "./animation.js";

export {
  TimeRangeSchema,
  AnchorSchema,
  SizeSpecSchema,
  TransformSchema,
  EffectInstanceDataSchema,
  BehaviorInstanceDataSchema,
  ActionInstanceDataSchema,
  LabelColorSchema,
  BlendModeSchema,
  TrackMatteModeSchema,
  TrackMatteSchema,
  NodeSchema,
  PathVertexSchema,
  PathDataSchema,
  CameraFollowSchema,
  CameraPathSchema,
  CameraSchema,
  MapSettingsSchema,
  MarkerSchema,
  GuideSchema,
  CompositionSchema,
  AssetDescriptorSchema,
  GeoDataDescriptorSchema,
  MapStyleDescriptorSchema,
  PaletteSchema,
  ProjectSettingsSchema,
  ProjectDocumentV1Schema,
  ProjectDocumentSchema,
  ProjectManifestV1Schema,
  ProjectManifestSchema,
  type TimeRange,
  type Anchor,
  type SizeSpec,
  type Transform,
  type EffectInstanceData,
  type BehaviorInstanceData,
  type ActionInstanceData,
  type LabelColor,
  type BlendMode,
  type TrackMatteMode,
  type TrackMatte,
  type Node,
  type PathVertex,
  type PathData,
  type CameraFollow,
  type CameraPath,
  type Camera,
  type MapSettings,
  type Marker,
  type Guide,
  type Composition,
  type AssetDescriptor,
  type GeoDataDescriptor,
  type MapStyleDescriptor,
  type Palette,
  type ProjectSettings,
  type ProjectDocument,
  type ProjectManifest,
} from "./project-document.js";

export {
  FutureSchemaVersionError,
  InvalidSchemaVersionError,
  MissingMigrationError,
  MigrationRegistry,
  projectMigrationRegistry,
  registerMigration,
  getSchemaVersion,
  assertSupportedSchemaVersion,
  migrateProjectDocument,
  FICTIONAL_V1_TO_V2_MIGRATION,
  createFictionalV2MigrationRegistry,
  parseProjectDocument,
  safeParseProjectDocument,
  type MigrationFunction,
  type Migration,
} from "./versioning.js";

export { createEmptyProjectDocument, type EmptyProjectOptions } from "./factory.js";

export {
  SceneTimeSchema,
  ScenePlaceSchema,
  SceneMetaSchema,
  SceneMapSchema,
  SceneDefaultsSchema,
  SceneFactionSchema,
  ScenePathStyleSchema,
  ScenePathSchema,
  SceneUnitSchema,
  SceneTimelineEntrySchema,
  SceneScriptV1Schema,
  SceneScriptSchema,
  VERB_CATALOG,
  parseSceneScript,
  safeParseSceneScript,
  type VerbCatalogEntry,
  type SceneTime,
  type ScenePlace,
  type SceneMeta,
  type SceneMap,
  type SceneDefaults,
  type SceneFaction,
  type ScenePath,
  type SceneUnit,
  type SceneTimelineEntry,
  type SceneScript,
} from "./scene-script.js";

export {
  createProjectDocumentJsonSchema,
  createSceneScriptJsonSchema,
  stableJsonStringify,
  type JsonSchemaDocument,
} from "./json-schema.js";
